// Generated by js_of_ocaml 3.0
(function(g){"use strict";var
ab=" : flags Open_text and Open_binary are not compatible",O="Sys_error",aa=224,$="Invalid_argument",q=1024,_="fs",N=57343,Z=512,Y="End_of_file",X="Failure",L="Undefined_recursive_module",M=" : flags Open_rdonly and Open_wronly are not compatible",K="([^/]*)",W="Stack_overflow",f=128,b="",V="^",G=" : file already exists",H=2048,I=56320,J=240,U="/static/",e=248,T="Not_found",F="Assert_failure",j="/",R="Sys_blocked_io",S="fd ",E="Out_of_memory",Q="Match_failure",P="Division_by_zero",az=0;function
r(){return az++}function
ag(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aL(g){for(var
h=b,c=h,a,j,d=0,i=g.length;d<i;d++){a=g.charCodeAt(d);if(a<f){for(var
e=d+1;e<i&&(a=g.charCodeAt(e))<f;e++);if(e-d>Z){c.substr(0,1);h+=c;c=b;h+=g.slice(d,e)}else
c+=g.slice(d,e);if(e==i)break;d=e}if(a<H){c+=String.fromCharCode(192|a>>6);c+=String.fromCharCode(f|a&63)}else
if(a<55296||a>=N)c+=String.fromCharCode(aa|a>>12,f|a>>6&63,f|a&63);else
if(a>=56319||d+1==i||(j=g.charCodeAt(d+1))<I||j>N)c+="\xef\xbf\xbd";else{d++;a=(a<<10)+j-56613888;c+=String.fromCharCode(J|a>>18,f|a>>12&63,f|a>>6&63,f|a&63)}if(c.length>q){c.substr(0,1);h+=c;c=b}}return h+c}function
aD(c,a){if(a.repeat)return a.repeat(c);var
d=b,e=0;if(c==0)return d;for(;;){if(c&1)d+=a;c>>=1;if(c==0)return d;a+=a;e++;if(e==9)a.slice(0,1)}}function
aO(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
A(c,d,a){var
e=String.fromCharCode;if(d==0&&a<=4096&&a==c.length)return e.apply(null,c);var
f=b;for(;0<a;d+=q,a-=q)f+=e.apply(null,aO(c,d,Math.min(a,q)));return f}function
ae(a){if(a.t==2)a.c+=aD(a.l-a.c.length,"\0");else
a.c=A(a.c,0,a.c.length);a.t=0}function
aK(g){for(var
l=b,d=b,i,h,j,a,c=0,k=g.length;c<k;c++){h=g.charCodeAt(c);if(h<f){for(var
e=c+1;e<k&&(h=g.charCodeAt(e))<f;e++);if(e-c>Z){d.substr(0,1);l+=d;d=b;l+=g.slice(c,e)}else
d+=g.slice(c,e);if(e==k)break;c=e}a=1;if(++c<k&&((j=g.charCodeAt(c))&-64)==f){i=j+(h<<6);if(h<aa){a=i-12416;if(a<f)a=1}else{a=2;if(++c<k&&((j=g.charCodeAt(c))&-64)==f){i=j+(i<<6);if(h<J){a=i-925824;if(a<H||a>=55295&&a<57344)a=2}else{a=3;if(++c<k&&((j=g.charCodeAt(c))&-64)==f&&h<245){a=j-63447168+(i<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){c-=a;d+="\ufffd"}else
if(a>65535)d+=String.fromCharCode(55232+(a>>10),I+(a&1023));else
d+=String.fromCharCode(a);if(d.length>q){d.substr(0,1);l+=d;d=b}}return l+d}function
aJ(a){switch(a.t){case
9:return a.c;default:ae(a);case
0:if(ag(a.c)){a.t=9;return a.c}a.t=8;case
8:return aK(a.c)}}function
n(c,a,b){this.t=c;this.c=a;this.l=b}n.prototype.toString=function(){return aJ(this)};function
ah(a){var
b=9;if(!ag(a))b=8,a=aL(a);return new
n(b,a,a.length)}function
aB(b,a){throw[0,b,a]}function
a(a){return new
n(0,a,a.length)}function
ak(c,b){aB(c,a(b))}var
d=[0];function
k(a){ak(d.Sys_error,a)}var
o=new
Array();function
au(e){var
a=o[e];if(!a.opened)k("Cannot flush a closed channel");if(!a.buffer||a.buffer==b)return 0;if(a.fd&&d.fds[a.fd]&&d.fds[a.fd].output){var
c=d.fds[a.fd].output;switch(c.length){case
2:c(e,a.buffer);break;default:c(a.buffer)}}a.buffer=b;return 0}if(g.process&&g.process.cwd)var
u=g.process.cwd();else
var
u="/static";if(u.slice(-1)!==j)u+=j;function
at(a){a=a
instanceof
n?a.toString():a;if(a.charCodeAt(0)!=47)a=u+a;var
e=a.split(j),c=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(c.length>1)c.pop();break;case".":break;case"":if(c.length==0)c.push(b);break;default:c.push(e[d]);break}c.orig=a;return c}function
aA(a){a=a
instanceof
n?a.toString():a;k(a+": No such file or directory")}function
aF(a){return new
n(4,a,a.length)}function
af(a){ak(d.Invalid_argument,a)}function
am(){af("index out of bounds")}function
aH(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
aE(b,a){if(a>>>0>=b.l)am();return aH(b,a)}function
p(a){if(a<0)af("String.create");return new
n(a?2:9,b,a)}function
aj(a){return a.l}function
z(b){if(g.Uint8Array)var
c=new(g.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
e=b.c,d=e.length,a=0;for(;a<d;a++)c[a]=e.charCodeAt(a);for(d=b.l;a<d;a++)c[a]=0;b.c=c;b.t=4;return c}function
t(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?A(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?A(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)z(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
ac(){}function
c(a){this.data=a}c.prototype=new
ac();c.prototype.truncate=function(a){var
b=this.data;this.data=p(a|0);t(b,0,this.data,0,a)};c.prototype.length=function(){return aj(this.data)};c.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=p(b+a),f=this.data;this.data=e;t(f,0,this.data,0,c)}t(d,g,this.data,b,a);return 0};c.prototype.read=function(c,a,d,b){var
e=this.length();t(this.data,c,a,d,b);return 0};c.prototype.read_one=function(a){return aE(this.data,a)};c.prototype.close=function(){};c.prototype.constructor=c;function
h(b,a){this.content={};this.root=b;this.lookupFun=a}h.prototype.nm=function(a){return this.root+a};h.prototype.lookup=function(b){if(!this.content[b]&&this.lookupFun){var
d=this.lookupFun(a(this.root),a(b));if(d!=0)this.content[b]=new
c(d[1])}};h.prototype.exists=function(a){this.lookup(a);return this.content[a]?1:0};h.prototype.readdir=function(d){var
g=d==b?b:d+j,h=new
RegExp(V+g+K),e={},c=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;c.push(a[1])}}return c};h.prototype.is_dir=function(a){var
e=a==b?b:a+j,f=new
RegExp(V+e+K),g=[];for(var
d
in
this.content){var
c=d.match(f);if(c)return 1}return 0};h.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};h.prototype.open=function(a,b){if(b.rdonly&&b.wronly)k(this.nm(a)+M);if(b.text&&b.binary)k(this.nm(a)+ab);this.lookup(a);if(this.content[a]){if(this.is_dir(a))k(this.nm(a)+" : is a directory");if(b.create&&b.excl)k(this.nm(a)+G);var
d=this.content[a];if(b.truncate)d.truncate();return d}else
if(b.create){this.content[a]=new
c(p(0));return this.content[a]}else
aA(this.nm(a))};h.prototype.register=function(d,b){if(this.content[d])k(this.nm(d)+G);if(b
instanceof
n)this.content[d]=new
c(b);else
if(b
instanceof
Array)this.content[d]=new
c(aF(b));else
if(b.toString){var
e=a(b.toString());this.content[d]=new
c(e)}};h.prototype.constructor=h;function
ad(a){if(a.t!=4)z(a);return a.c}function
aI(a,c,b){b&=255;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}z(a)}a.c[c]=b;return 0}function
aG(b,a,c){if(a>>>0>=b.l)am();return aI(b,a,c)}var
y=g.Buffer;function
m(a){this.fs=require(_);this.fd=a}m.prototype=new
ac();m.prototype.truncate=function(a){this.fs.ftruncateSync(this.fd,a|0)};m.prototype.length=function(){return this.fs.fstatSync(this.fd).size};m.prototype.write=function(f,b,c,e){var
a=ad(b);if(!a
instanceof
g.Uint8Array)a=new(g.Uint8Array)(a);var
d=new
y(a);this.fs.writeSync(this.fd,d,c,e,f);return 0};m.prototype.read=function(h,d,c,f){var
a=ad(d);if(!(a
instanceof
g.Uint8Array))a=new(g.Uint8Array)(a);var
e=new
y(a);this.fs.readSync(this.fd,e,c,f,h);for(var
b=0;b<f;b++)aG(d,c+b,e[c+b]);return 0};m.prototype.read_one=function(c){var
b=new(g.Uint8Array)(1),a=new
y(b);this.fs.readSync(this.fd,a,0,1,c);return a[0]};m.prototype.close=function(){this.fs.closeSync(this.fd)};m.prototype.constructor=m;function
l(a){this.fs=require(_);this.root=a}l.prototype.nm=function(a){return this.root+a};l.prototype.exists=function(a){return this.fs.existsSync(this.nm(a))?1:0};l.prototype.readdir=function(a){return this.fs.readdirSync(this.nm(a))};l.prototype.is_dir=function(a){return this.fs.statSync(this.nm(a)).isDirectory()?1:0};l.prototype.unlink=function(a){var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b};l.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}var
d=this.fs.openSync(this.nm(f),b);return new
m(d)};l.prototype.rename=function(b,a){this.fs.renameSync(this.nm(b),this.nm(a))};l.prototype.constructor=l;var
s=[];if(typeof
require=="undefined")s.push({path:j,device:new
h(j)});else
s.push({path:j,device:new
l(j)});s.push({path:U,device:new
h(U)});function
aP(b){var
f=at(b),b=f.join(j),e=b+j,c;for(var
d=0;d<s.length;d++){var
a=s[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
al(e,f){var
b=o[e],d=a(f),c=aj(d);b.file.write(b.offset,d,0,c);b.offset+=c;return 0}function
aM(a){var
b=g;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
aN(a){var
b=g;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}function
v(c,f,e,a){if(d.fds===undefined)d.fds=new
Array();a=a?a:{};var
b={};b.file=e;b.offset=a.append?e.length():0;b.flags=a;b.output=f;d.fds[c]=b;if(!d.fd_last_idx||c>d.fd_last_idx)d.fd_last_idx=c;return c}function
aQ(c,b,h){var
a={};while(b){switch(b[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}b=b[2]}if(a.rdonly&&a.wronly)k(c.toString()+M);if(a.text&&a.binary)k(c.toString()+ab);var
e=aP(c),f=e.device.open(e.rest,a),g=d.fd_last_idx?d.fd_last_idx:0;return v(g+1,al,f,a)}v(0,al,new
c(p(0)));v(1,aN,new
c(p(0)));v(2,aM,new
c(p(0)));function
av(c){var
b=d.fds[c];if(b.flags.wronly)k(S+c+" is writeonly");var
a={file:b.file,offset:b.offset,fd:c,opened:true,out:false,refill:null};o[a.fd]=a;return a.fd}function
ai(e){var
c=d.fds[e];if(c.flags.rdonly)k(S+e+" is readonly");var
a={file:c.file,offset:c.offset,fd:e,opened:true,out:true,buffer:b};o[a.fd]=a;return a.fd}function
aw(){var
b=0;for(var
a=0;a<o.length;a++)if(o[a]&&o[a].opened&&o[a].out)b=[0,o[a],b];return b}function
ay(a){return a
instanceof
Array?a[0]:a
instanceof
n?252:1e3}function
i(c,b,a){d[c+1]=b;if(a)d[a]=b}var
ax={};function
as(a){if((a.t&6)!=0)ae(a);return a.c}function
aC(a,b){ax[as(a)]=b;return 0}i(11,[e,a(L),-12],L);i(10,[e,a(F),-11],F);i(9,[e,a(R),-10],R);i(8,[e,a(W),-9],W);i(7,[e,a(Q),-8],Q);i(6,[e,a(T),-7],T);i(5,[e,a(P),-6],P);i(4,[e,a(Y),-5],Y);i(3,[e,a($),-4],$);i(2,[e,a(X),-3],X);i(1,[e,a(O),-2],O);i(0,[e,a(E),-1],E);r(0);av(0);ai(1);ai(2);r(0);r(0);var
B=[0,0],ar=a("Js.Error");function
C(a){B[1]=[0,a,B[1]];return 0}var
w=g,aq=w.Array,D=[e,ar,r(0)],x=[0,D,{}],ap=undefined,ao=ay(x)===e?x:x[1];aC(a("jsError"),ao);(function(a){throw a});C(function(a){return a[1]===D?[0,ah(a[2].toString())]:0});C(function(a){return a
instanceof
aq?0:[0,ah(a.toString())]});r(0);w.HTMLElement===ap;w.alert("hello world");function
an(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{au(d)}catch(a){}var
a=c;continue}return 0}}an(aw(0));return}(function(){return this}()));
