// Generated by js_of_ocaml 3.0
(function(g){"use strict";var
ai=" : flags Open_text and Open_binary are not compatible",V="Sys_error",ah=224,ag="Invalid_argument",r=1024,af="fs",U=57343,ae=512,ad="End_of_file",ac="Failure",S="Undefined_recursive_module",T=" : flags Open_rdonly and Open_wronly are not compatible",R="([^/]*)",ab="Stack_overflow",f=128,b="",aa="^",N=" : file already exists",O=2048,P=56320,Q=240,$="/static/",e=248,_="Not_found",M="Assert_failure",j="/",Y="Sys_blocked_io",Z="fd ",L="Out_of_memory",X="Match_failure",W="Division_by_zero",aL=0;function
s(){return aL++}function
an(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aX(g){for(var
h=b,c=h,a,j,d=0,i=g.length;d<i;d++){a=g.charCodeAt(d);if(a<f){for(var
e=d+1;e<i&&(a=g.charCodeAt(e))<f;e++);if(e-d>ae){c.substr(0,1);h+=c;c=b;h+=g.slice(d,e)}else
c+=g.slice(d,e);if(e==i)break;d=e}if(a<O){c+=String.fromCharCode(192|a>>6);c+=String.fromCharCode(f|a&63)}else
if(a<55296||a>=U)c+=String.fromCharCode(ah|a>>12,f|a>>6&63,f|a&63);else
if(a>=56319||d+1==i||(j=g.charCodeAt(d+1))<P||j>U)c+="\xef\xbf\xbd";else{d++;a=(a<<10)+j-56613888;c+=String.fromCharCode(Q|a>>18,f|a>>12&63,f|a>>6&63,f|a&63)}if(c.length>r){c.substr(0,1);h+=c;c=b}}return h+c}function
aP(c,a){if(a.repeat)return a.repeat(c);var
d=b,e=0;if(c==0)return d;for(;;){if(c&1)d+=a;c>>=1;if(c==0)return d;a+=a;e++;if(e==9)a.slice(0,1)}}function
a0(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
C(c,d,a){var
e=String.fromCharCode;if(d==0&&a<=4096&&a==c.length)return e.apply(null,c);var
f=b;for(;0<a;d+=r,a-=r)f+=e.apply(null,a0(c,d,Math.min(a,r)));return f}function
al(a){if(a.t==2)a.c+=aP(a.l-a.c.length,"\0");else
a.c=C(a.c,0,a.c.length);a.t=0}function
aW(g){for(var
l=b,d=b,i,h,j,a,c=0,k=g.length;c<k;c++){h=g.charCodeAt(c);if(h<f){for(var
e=c+1;e<k&&(h=g.charCodeAt(e))<f;e++);if(e-c>ae){d.substr(0,1);l+=d;d=b;l+=g.slice(c,e)}else
d+=g.slice(c,e);if(e==k)break;c=e}a=1;if(++c<k&&((j=g.charCodeAt(c))&-64)==f){i=j+(h<<6);if(h<ah){a=i-12416;if(a<f)a=1}else{a=2;if(++c<k&&((j=g.charCodeAt(c))&-64)==f){i=j+(i<<6);if(h<Q){a=i-925824;if(a<O||a>=55295&&a<57344)a=2}else{a=3;if(++c<k&&((j=g.charCodeAt(c))&-64)==f&&h<245){a=j-63447168+(i<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){c-=a;d+="\ufffd"}else
if(a>65535)d+=String.fromCharCode(55232+(a>>10),P+(a&1023));else
d+=String.fromCharCode(a);if(d.length>r){d.substr(0,1);l+=d;d=b}}return l+d}function
aV(a){switch(a.t){case
9:return a.c;default:al(a);case
0:if(an(a.c)){a.t=9;return a.c}a.t=8;case
8:return aW(a.c)}}function
n(c,a,b){this.t=c;this.c=a;this.l=b}n.prototype.toString=function(){return aV(this)};function
ao(a){var
b=9;if(!an(a))b=8,a=aX(a);return new
n(b,a,a.length)}function
aN(b,a){throw[0,b,a]}function
a(a){return new
n(0,a,a.length)}function
ar(c,b){aN(c,a(b))}var
d=[0];function
k(a){ar(d.Sys_error,a)}var
o=new
Array();function
aG(e){var
a=o[e];if(!a.opened)k("Cannot flush a closed channel");if(!a.buffer||a.buffer==b)return 0;if(a.fd&&d.fds[a.fd]&&d.fds[a.fd].output){var
c=d.fds[a.fd].output;switch(c.length){case
2:c(e,a.buffer);break;default:c(a.buffer)}}a.buffer=b;return 0}if(g.process&&g.process.cwd)var
x=g.process.cwd();else
var
x="/static";if(x.slice(-1)!==j)x+=j;function
aF(a){a=a
instanceof
n?a.toString():a;if(a.charCodeAt(0)!=47)a=x+a;var
e=a.split(j),c=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(c.length>1)c.pop();break;case".":break;case"":if(c.length==0)c.push(b);break;default:c.push(e[d]);break}c.orig=a;return c}function
aM(a){a=a
instanceof
n?a.toString():a;k(a+": No such file or directory")}function
aR(a){return new
n(4,a,a.length)}function
am(a){ar(d.Invalid_argument,a)}function
at(){am("index out of bounds")}function
aT(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
aQ(b,a){if(a>>>0>=b.l)at();return aT(b,a)}function
p(a){if(a<0)am("String.create");return new
n(a?2:9,b,a)}function
aq(a){return a.l}function
B(b){if(g.Uint8Array)var
c=new(g.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
e=b.c,d=e.length,a=0;for(;a<d;a++)c[a]=e.charCodeAt(a);for(d=b.l;a<d;a++)c[a]=0;b.c=c;b.t=4;return c}function
w(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?C(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?C(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)B(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
aj(){}function
c(a){this.data=a}c.prototype=new
aj();c.prototype.truncate=function(a){var
b=this.data;this.data=p(a|0);w(b,0,this.data,0,a)};c.prototype.length=function(){return aq(this.data)};c.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=p(b+a),f=this.data;this.data=e;w(f,0,this.data,0,c)}w(d,g,this.data,b,a);return 0};c.prototype.read=function(c,a,d,b){var
e=this.length();w(this.data,c,a,d,b);return 0};c.prototype.read_one=function(a){return aQ(this.data,a)};c.prototype.close=function(){};c.prototype.constructor=c;function
h(b,a){this.content={};this.root=b;this.lookupFun=a}h.prototype.nm=function(a){return this.root+a};h.prototype.lookup=function(b){if(!this.content[b]&&this.lookupFun){var
d=this.lookupFun(a(this.root),a(b));if(d!=0)this.content[b]=new
c(d[1])}};h.prototype.exists=function(a){this.lookup(a);return this.content[a]?1:0};h.prototype.readdir=function(d){var
g=d==b?b:d+j,h=new
RegExp(aa+g+R),e={},c=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;c.push(a[1])}}return c};h.prototype.is_dir=function(a){var
e=a==b?b:a+j,f=new
RegExp(aa+e+R),g=[];for(var
d
in
this.content){var
c=d.match(f);if(c)return 1}return 0};h.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};h.prototype.open=function(a,b){if(b.rdonly&&b.wronly)k(this.nm(a)+T);if(b.text&&b.binary)k(this.nm(a)+ai);this.lookup(a);if(this.content[a]){if(this.is_dir(a))k(this.nm(a)+" : is a directory");if(b.create&&b.excl)k(this.nm(a)+N);var
d=this.content[a];if(b.truncate)d.truncate();return d}else
if(b.create){this.content[a]=new
c(p(0));return this.content[a]}else
aM(this.nm(a))};h.prototype.register=function(d,b){if(this.content[d])k(this.nm(d)+N);if(b
instanceof
n)this.content[d]=new
c(b);else
if(b
instanceof
Array)this.content[d]=new
c(aR(b));else
if(b.toString){var
e=a(b.toString());this.content[d]=new
c(e)}};h.prototype.constructor=h;function
ak(a){if(a.t!=4)B(a);return a.c}function
aU(a,c,b){b&=255;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}B(a)}a.c[c]=b;return 0}function
aS(b,a,c){if(a>>>0>=b.l)at();return aU(b,a,c)}var
A=g.Buffer;function
m(a){this.fs=require(af);this.fd=a}m.prototype=new
aj();m.prototype.truncate=function(a){this.fs.ftruncateSync(this.fd,a|0)};m.prototype.length=function(){return this.fs.fstatSync(this.fd).size};m.prototype.write=function(f,b,c,e){var
a=ak(b);if(!a
instanceof
g.Uint8Array)a=new(g.Uint8Array)(a);var
d=new
A(a);this.fs.writeSync(this.fd,d,c,e,f);return 0};m.prototype.read=function(h,d,c,f){var
a=ak(d);if(!(a
instanceof
g.Uint8Array))a=new(g.Uint8Array)(a);var
e=new
A(a);this.fs.readSync(this.fd,e,c,f,h);for(var
b=0;b<f;b++)aS(d,c+b,e[c+b]);return 0};m.prototype.read_one=function(c){var
b=new(g.Uint8Array)(1),a=new
A(b);this.fs.readSync(this.fd,a,0,1,c);return a[0]};m.prototype.close=function(){this.fs.closeSync(this.fd)};m.prototype.constructor=m;function
l(a){this.fs=require(af);this.root=a}l.prototype.nm=function(a){return this.root+a};l.prototype.exists=function(a){return this.fs.existsSync(this.nm(a))?1:0};l.prototype.readdir=function(a){return this.fs.readdirSync(this.nm(a))};l.prototype.is_dir=function(a){return this.fs.statSync(this.nm(a)).isDirectory()?1:0};l.prototype.unlink=function(a){var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b};l.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}var
d=this.fs.openSync(this.nm(f),b);return new
m(d)};l.prototype.rename=function(b,a){this.fs.renameSync(this.nm(b),this.nm(a))};l.prototype.constructor=l;var
t=[];if(typeof
require=="undefined")t.push({path:j,device:new
h(j)});else
t.push({path:j,device:new
l(j)});t.push({path:$,device:new
h($)});function
a1(b){var
f=aF(b),b=f.join(j),e=b+j,c;for(var
d=0;d<t.length;d++){var
a=t[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
as(e,f){var
b=o[e],d=a(f),c=aq(d);b.file.write(b.offset,d,0,c);b.offset+=c;return 0}function
aY(a){var
b=g;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
aZ(a){var
b=g;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}function
y(c,f,e,a){if(d.fds===undefined)d.fds=new
Array();a=a?a:{};var
b={};b.file=e;b.offset=a.append?e.length():0;b.flags=a;b.output=f;d.fds[c]=b;if(!d.fd_last_idx||c>d.fd_last_idx)d.fd_last_idx=c;return c}function
a2(c,b,h){var
a={};while(b){switch(b[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}b=b[2]}if(a.rdonly&&a.wronly)k(c.toString()+T);if(a.text&&a.binary)k(c.toString()+ai);var
e=a1(c),f=e.device.open(e.rest,a),g=d.fd_last_idx?d.fd_last_idx:0;return y(g+1,as,f,a)}y(0,as,new
c(p(0)));y(1,aZ,new
c(p(0)));y(2,aY,new
c(p(0)));function
aH(c){var
b=d.fds[c];if(b.flags.wronly)k(Z+c+" is writeonly");var
a={file:b.file,offset:b.offset,fd:c,opened:true,out:false,refill:null};o[a.fd]=a;return a.fd}function
ap(e){var
c=d.fds[e];if(c.flags.rdonly)k(Z+e+" is readonly");var
a={file:c.file,offset:c.offset,fd:e,opened:true,out:true,buffer:b};o[a.fd]=a;return a.fd}function
aI(){var
b=0;for(var
a=0;a<o.length;a++)if(o[a]&&o[a].opened&&o[a].out)b=[0,o[a],b];return b}function
aK(a){return a
instanceof
Array?a[0]:a
instanceof
n?252:1e3}function
i(c,b,a){d[c+1]=b;if(a)d[a]=b}var
aJ={};function
aE(a){if((a.t&6)!=0)al(a);return a.c}function
aO(a,b){aJ[aE(a)]=b;return 0}var
D=[e,a(M),-11];i(11,[e,a(S),-12],S);i(10,D,M);i(9,[e,a(Y),-10],Y);i(8,[e,a(ab),-9],ab);i(7,[e,a(X),-8],X);i(6,[e,a(_),-7],_);i(5,[e,a(W),-6],W);i(4,[e,a(ad),-5],ad);i(3,[e,a(ag),-4],ag);i(2,[e,a(ac),-3],ac);i(1,[e,a(V),-2],V);i(0,[e,a(L),-1],L);s(0);aH(0);ap(1);ap(2);s(0);s(0);var
E=[0,0],az=a("Js.Error"),aC=a("h1"),aB=a("div"),aD=[0,a("gui.ml"),10,20];function
F(a){E[1]=[0,a,E[1]];return 0}var
q=g,G=null,ay=q.Array,H=[e,az,s(0)],z=[0,H,{}],aw=undefined,ax=false,av=aK(z)===e?z:z[1];aO(a("jsError"),av);(function(a){throw a});F(function(a){return a[1]===H?[0,ao(a[2].toString())]:0});F(function(a){return a
instanceof
ay?0:[0,ao(a.toString())]});function
u(b,a){b.appendChild(a);return 0}var
aA=q.document;function
I(b,a){return b.createElement(a.toString())}function
J(a){return I(a,aB)}s(0);q.HTMLElement===aw;var
v=q.document;function
K(e){var
a=aA.getElementById("gui");if(a==G)throw[0,D,aD];a.style.cssText="font-family: sans-serif; background-color: #00cc00;";var
b=I(v,aC);u(b,v.createTextNode("The Legend of Tomnjam"));u(a,b);var
d=J(v),c=J(v);u(c,d);u(a,c);return ax}q.onload=function(a){if(1-(a==G?1:0)){var
c=K(a);if(1-(c|0))a.preventDefault();return c}var
d=event,b=K(d);if(1-(b|0))d.returnValue=b;return b};function
au(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{aG(d)}catch(a){}var
a=c;continue}return 0}}au(aI(0));return}(function(){return this}()));
